#!/usr/bin/env node
'use strict';
const fs = require('fs');
const path = require('path');

// ── Seeded RNG ────────────────────────────────────────────────────
function makePrng(seed) {
  let s = seed >>> 0;
  return () => {
    s += 0x6D2B79F5;
    let t = Math.imul(s ^ (s >>> 15), 1 | s);
    t ^= t + Math.imul(t ^ (t >>> 7), 61 | t);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
function shuffle(arr, rng) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}
function pick(arr, rng) { return arr[Math.floor(rng() * arr.length)]; }
function pickN(arr, n, rng) { return shuffle(arr, rng).slice(0, n); }

// ── Curated sets ──────────────────────────────────────────────────
const SILENT_SET = new Set([
  'KNIGHT','KNIFE','WRAP','GNOME','LAMB','THUMB','CLIMB','GHOST','SWORD','KNOT',
  'WRECK','GNAT','WRIST','KNEEL','KNOCK','DUMB','COMB','NUMB','DEBT','DOUBT',
  'WREN','WRITE','PSALM','CASTLE','FASTEN','LISTEN','SOFTEN','WHISTLE','NESTLE',
  'BUSTLE','WRESTLE','THISTLE','BALLET','BUFFET','BOUQUET','DEPOT','DEBUT',
  'MUSCLE','HUSTLE','ISLAND','AISLE','CALM','PALM','WALK','TALK','CHALK','HALF',
  'CALF','WOULD','COULD','SHOULD','FOLK','YOLK','SALMON','BALM','HOUR','HONEST',
  'HONOR','PLUMB','KNAVE','KNACK','RHYME','RHINO','TOMB','WOMB','BOMB','GNASH',
  'KNEW','KNIT','KNOLL','WREATH','WRONG','WROTE','WRING','WRENCH','GNAW','GNARL',
  'LIMB','CRUMB','HYMN','COLUMN','AUTUMN','SOLEMN','DAMN','CONDEMN','HASTEN',
]);

const COMPOUND_SET = new Set([
  'AIRFIELD','AIRCRAFT','AIRLOCK','AIRPORT','ARMCHAIR','BACKDROP','BACKFIRE',
  'BACKPACK','BACKYARD','BASEBALL','BATHROOM','BEDROOM','BOOKWORM','BRAINWAVE',
  'BULLSEYE','CAMPFIRE','CATNAP','COBWEB','CORNFIELD','CROSSBOW','CUPCAKE',
  'DAREDEVIL','DAYBREAK','DAYDREAM','DEADLINE','DEWDROP','DOORSTEP','DOWNFALL',
  'DOWNPOUR','DRIFTWOOD','DRUMROLL','DUMBBELL','DUSTPAN','EARDRUM','EARTHQUAKE',
  'EGGSHELL','EYEBROW','FAIRGROUND','FIREPLACE','FIRESIDE','FLAGSHIP','FLASHBACK',
  'FLOODGATE','FOOTPRINT','FOOTSTEP','FORKLIFT','FROSTBITE','GODMOTHER','GRASSLAND',
  'GRAVEYARD','GREENHOUSE','GUNSHOT','HANDBOOK','HANDSHAKE','HANGOVER','HEADBAND',
  'HEADLIGHT','HEARTBEAT','HEATWAVE','HEDGEHOG','HIGHLAND','HILLSIDE','HOMELAND',
  'HONEYBEE','HONEYDEW','HORSEBACK','HOURGLASS','HOUSEWORK','ICEBERG','ICECAP',
  'JACKPOT','JAWBONE','JELLYFISH','KEYBOARD','KEYSTONE','LANDMARK','LANDSLIDE',
  'LIFEGUARD','LIGHTHOUSE','LIPSTICK','LIVESTOCK','LOCKDOWN','LOVEBIRD','MAINLAND',
  'MASTERPIECE','MIDNIGHT','MILESTONE','MILLSTONE','MOONLIGHT','MOONRISE','NAMESAKE',
  'NIGHTFALL','NIGHTMARE','NOTEBOOK','OFFSPRING','OUTBREAK','OUTCAST','OUTLAW',
  'OUTPOST','OVERTURE','PANCAKE','PATHWAY','PITFALL','PLAYOFF','POSTCARD',
  'QUICKSAND','RAILROAD','RAINBOW','RAINFALL','RAINSTORM','RATTLESNAKE','ROADBLOCK',
  'ROOFTOP','ROOMMATE','RUNWAY','SALTWATER','SANDSTONE','SCARECROW','SCRAPBOOK',
  'SEASHELL','SEASHORE','SHIPWRECK','SHORTCUT','SHOWDOWN','SIDEWALK','SKYSCRAPER',
  'SLAPSTICK','SNOWBALL','SNOWFLAKE','SNOWSTORM','STARFISH','STARLIGHT','STEPMOTHER',
  'STONEWALL','STOPWATCH','STOREFRONT','STRAWBERRY','SUNBEAM','SUNBURN','SUNFLOWER',
  'SUNLIGHT','SUNRISE','SUNSCREEN','SUNSET','SUNSHINE','SURFBOARD','SWORDFISH',
  'TAILGATE','THUMBPRINT','THUNDERSTORM','TIDEWATER','TOADSTOOL','TOMBSTONE',
  'TOOTHBRUSH','TOOTHPASTE','TOWNSHIP','TRADEMARK','TREEHOUSE','TWILIGHT',
  'UNDERGROUND','UNDERTOW','UPBEAT','UPKEEP','UPROAR','UPSIDE','UPTOWN','UPSURGE',
  'VIEWPOINT','VINEYARD','WALLPAPER','WAREHOUSE','WARSHIP','WATERFALL','WATERFRONT',
  'WATERMARK','WATERSHED','WEEKDAY','WEEKEND','WHIRLPOOL','WHIRLWIND','WILDFIRE',
  'WINDFALL','WINDMILL','WINDPIPE','WISHBONE','WOODLAND','WORKSHEET','WORLDWIDE',
  'WRISTWATCH',
]);

const SYLLABLE_SET = new Set([
  'ABANDON','ABSOLUTE','ACCIDENT','AFTERNOON','AGENCY','ALREADY','AMAZING',
  'AMBULANCE','ANOTHER','ANYMORE','ANIMAL','APPETITE','ATMOSPHERE','ATTENTION',
  'ATTITUDE','AVENUE','BEAUTIFUL','BEGINNING','BICYCLE','CALENDAR','CAPITAL',
  'CATEGORY','CELEBRATE','CINEMA','CITIZEN','COMPUTER','CRIMINAL','DECIMAL',
  'DEFINITION','DEMOCRACY','DESPERATE','DIGITAL','DINOSAUR','DIRECTION','DOCUMENT',
  'DOMINO','DRAMATIC','EDUCATE','ELECTION','ENERGY','ENVELOPE','ESTIMATE',
  'EVIDENCE','EXAMPLE','EXERCISE','FANTASY','FINALLY','FOLLOWING','FORMULA',
  'GENERATE','GOVERNMENT','GUARANTEE','GYMNASIUM','HORIZON','HURRICANE','IGNORANT',
  'IMAGINE','IMPORTANT','INJURY','INNOCENT','INTERNET','INTRODUCE','JEALOUSY',
  'MATERIAL','MENTIONED','MILITARY','MINERAL','MINIMUM','MIRACLE','NEGATIVE',
  'NOVEMBER','OBVIOUS','OCTOBER','ORDINARY','ORGANIZE','OTHERWISE','PARAGRAPH',
  'PARTICULAR','PENALTY','PROBABLY','RADICAL','REACTION','REMEMBER','RESIDENT',
  'SATURDAY','SENATOR','SKELETON','SPECIFIC','STRATEGY','SUDDENLY','TOMORROW',
  'TOGETHER','UMBRELLA','UNIVERSE','USUALLY','VACATION','VERTICAL','VICTORY',
  'VIOLENCE','WONDERFUL',
]);

const PALINDROME_LIST = [
  'KAYAK','RADAR','LEVEL','CIVIC','MADAM','REFER','ROTOR','TENET',
  'NOON','DEED','POOP','PEEP','SEES','RACECAR','STATS','REVIVER',
];

// ── Category pools ────────────────────────────────────────────────
const CATEGORY_POOL = {
  // ── Existing categories ───────────────────────────────────────
  animal: [
    'TIGER','WOLF','HAWK','COBRA','FINCH','SHARK','CRANE','HERON','BISON','RAVEN',
    'CROW','DEER','OTTER','FALCON','FROG','ROBIN','PARROT','JAGUAR','COYOTE','GAZELLE',
    'WALRUS','DOLPHIN','BASS','NEWT','LARK','MOLE','MOTH','WASP','VIPER','LYNX',
    'GECKO','BADGER','PANDA','MOOSE','SWIFT','QUAIL','MARTEN','WEASEL','FERRET','SHREW',
    'LEMUR','GIBBON','JACKAL','BOBCAT','COUGAR','TROUT','SALMON','BEETLE','SPIDER','TOAD',
    'STORK','IBIS','GROUSE','TOUCAN','MAGPIE','CONDOR','OSPREY','KESTREL','VOLE','BABOON',
    'CHEETAH','HYENA','GORILLA','BUFFALO','IMPALA','CARIBOU','NARWHAL','ORCA','MINNOW',
    'PIKE','SNIPE','PLOVER','DINGO','TAPIR','LLAMA','ALPACA','STOAT','PIGEON','SPARROW',
    'THRUSH','WARBLER','LINNET','BUNTING','CURLEW','AVOCET','BITTERN','KITE','BUZZARD',
    'HARRIER','GOSHAWK','MARTIN','SWALLOW','SKYLARK','WHEATEAR','REDSTART','WAXWING',
  ],
  color: [
    'SCARLET','CRIMSON','TEAL','INDIGO','VIOLET','MAROON','AZURE','MAUVE',
    'LILAC','CYAN','MAGENTA','LAVENDER','FUCHSIA','SAFFRON','MUSTARD','KHAKI',
    'TAUPE','SIENNA','OCHRE','VERMILION','BRONZE','ROSE','PERIWINKLE',
    'CHARTREUSE','CERISE','BUFF','FAWN','ECRU','UMBER','CARMINE',
    'CERULEAN','SEPIA','RUSSET','CLARET','DAMSON','AUBURN',
    'FLAXEN','TAWNY','SLATE','PEWTER','GUNMETAL','CHARCOAL',
    'ALABASTER','LINEN','SAND','BISQUE','BLUSH','PUCE',
  ],
  sport: [
    'TENNIS','SOCCER','RUGBY','CRICKET','HOCKEY','BOXING','SKIING','SURFING','ROWING',
    'CYCLING','SWIMMING','DIVING','ARCHERY','FENCING','WRESTLING','JUDO','GOLF','POLO',
    'SQUASH','BADMINTON','VOLLEYBALL','BASKETBALL','BASEBALL','HANDBALL','CROQUET',
    'DARTS','SNOOKER','CURLING','MARATHON','HURDLES','JAVELIN','DISCUS','TRIATHLON',
    'BIATHLON','PENTATHLON','LACROSSE','NETBALL','SOFTBALL','BOWLING','KARATE',
    'TAEKWONDO','SUMO','SAILING','CANOEING','CLIMBING','GYMNASTICS','WEIGHTLIFTING',
    'SHOOTING','BOBSLED','LUGE','SKELETON','SKATEBOARDING','WAKEBOARDING',
  ],
  vehicle: [
    'TRUCK','TRAIN','PLANE','YACHT','CANOE','KAYAK','BARGE','FERRY','TRAM','ROCKET',
    'SHUTTLE','GLIDER','SCOOTER','MOPED','BICYCLE','SEDAN','COUPE','WAGON','JEEP',
    'GONDOLA','CATAMARAN','FRIGATE','SUBMARINE','HELICOPTER','BALLOON','MONORAIL',
    'TROLLEY','TANKER','DINGHY','TUGBOAT','TRAWLER','BIPLANE','SLED','SNOWMOBILE',
    'UNICYCLE','TRICYCLE','MOTORBIKE','CARAVAN','MINIBUS','AMBULANCE',
    'BULLDOZER','EXCAVATOR','FORKLIFT','TRACTOR','HARVESTER','SNOWPLOW','STEAMBOAT',
    'HOVERCRAFT','AIRSHIP','ZEPPELIN','SPACECRAFT','ROVER','FREIGHTER','DESTROYER',
    'CRUISER','BATTLESHIP','CARRIER','PADDLEBOAT','LANDER','CAPSULE',
  ],
  food: [
    'MANGO','PEACH','PLUM','GRAPE','APPLE','LEMON','MELON','OLIVE','ONION','CARROT',
    'CELERY','GINGER','GARLIC','PEPPER','TOMATO','POTATO','SPINACH','CABBAGE','TURNIP',
    'RADISH','KALE','LEEK','BASIL','THYME','SAGE','MINT','ALMOND','WALNUT','PECAN',
    'CASHEW','BARLEY','CHEESE','BUTTER','HONEY','PICKLE','CURRY','TACO','SALSA',
    'HUMMUS','FALAFEL','KEBAB','PAPAYA','GUAVA','LYCHEE','KUMQUAT','PERSIMMON',
    'POMELO','TANGERINE','NECTARINE','APRICOT','CHERRY','BLUEBERRY','RASPBERRY',
    'STRAWBERRY','BLACKBERRY','CRANBERRY','GOOSEBERRY','ELDERBERRY','MULBERRY',
    'QUINCE','FENNEL','ARTICHOKE','ASPARAGUS','BROCCOLI','CAULIFLOWER','COURGETTE',
    'AUBERGINE','AVOCADO','BEETROOT','PARSNIP','SWEDE','CELERIAC','KOHLRABI','OKRA',
    'SORREL','WATERCRESS','RADICCHIO','SAMPHIRE','TAMARIND','JICAMA','CASSAVA',
    'PLANTAIN','LOQUAT','CHERIMOYA',
  ],
  instrument: [
    'GUITAR','VIOLIN','CELLO','FLUTE','OBOE','CLARINET','TRUMPET','TROMBONE','TUBA',
    'BANJO','MANDOLIN','UKULELE','SITAR','LUTE','HARP','PIANO','ORGAN','ACCORDION',
    'HARMONICA','KAZOO','XYLOPHONE','MARIMBA','CYMBAL','TAMBOURINE','BONGO','CONGA',
    'SNARE','BASSOON','PICCOLO','SAXOPHONE','CORNET','BUGLE','RECORDER','BAGPIPE',
    'DULCIMER','ZITHER','AUTOHARP','CITTERN','REBEC','ANGKLUNG','STEELPAN','MBIRA',
    'BALAFON','KORA','DJEMBE','TABLA','SAROD','VEENA','SANTOOR','DUDUK','ERHU',
    'GUZHENG','PIPA','DIZI','SHAMISEN','KOTO','SHAKUHACHI','BIWA',
  ],
  weather: [
    'STORM','FROST','SLEET','HAIL','SNOW','RAIN','DRIZZLE','FOG','MIST','CLOUD',
    'THUNDER','TORNADO','CYCLONE','TYPHOON','HURRICANE','BLIZZARD','DROUGHT','FLOOD',
    'GALE','SQUALL','GUST','BREEZE','MONSOON','TEMPEST','DOWNPOUR','SHOWER','FLURRY',
    'ICICLE','RAINBOW','WHIRLWIND','SUNSHINE','LIGHTNING','OVERCAST','SMOG','HAZE',
    'SLUSH','FREEZE','THAW','HEATWAVE','DAMP','HUMID','ARID','BALMY','BREEZY',
    'CRISP','FOGGY','FROSTY','RAINY','SNOWY','STORMY','SUNNY','WINDY','MISTY',
    'CLOUDY','WINTRY','SULTRY',
  ],
  emotion: [
    'GRIEF','BLISS','FURY','DREAD','ENVY','PRIDE','SHAME','GUILT','HOPE','LOVE',
    'HATE','FEAR','RAGE','CALM','JOY','ANGST','GLOOM','CHEER','SCORN','PITY',
    'AWE','SHOCK','PANIC','DOUBT','TRUST','DISGUST','DELIGHT','SORROW','ELATION',
    'DESPAIR','CONTENT','SERENITY','LONGING','ANGUISH','ECSTASY','MELANCHOLY',
    'EUPHORIA','NOSTALGIA','YEARNING','REMORSE','REGRET','RELIEF','GRATITUDE',
    'EMPATHY','SYMPATHY','JEALOUSY','BITTERNESS','RESENTMENT','CONTEMPT','LOATHING',
    'TERROR','HORROR','ALARM','DISMAY','DISTRESS','AGONY','MISERY','FORLORN',
    'DEJECTED','GLOOMY','GLUM','MOROSE','MOURNFUL','WISTFUL','PENSIVE','BROODING',
  ],
  body: [
    'THUMB','ELBOW','SPINE','SKULL','ANKLE','WRIST','CHEEK','BROW','CHIN','SCALP',
    'PALM','CALF','SHIN','HEEL','LOBE','IRIS','PUPIL','NOSTRIL','TEMPLE','STERNUM',
    'PELVIS','FEMUR','TIBIA','FIBULA','RADIUS','ULNA','HUMERUS','PATELLA','THORAX',
    'LARYNX','TONSIL','TRACHEA','CORNEA','RETINA','JAWBONE','KNEECAP','RIBCAGE',
    'COLLARBONE','HIPBONE','SHINBONE','THIGHBONE','BREASTBONE','BACKBONE','TAILBONE',
    'CHEEKBONE','EARDRUM','EARLOBE','EYEBROW','EYELID','FOREHEAD','KNUCKLE',
    'FINGERTIP','TOENAIL','THUMBNAIL','ARMPIT','NAVEL','INSTEP','SOLE','NAPE',
    'THROAT','TORSO','SHOULDER','WAIST',
  ],
  country: [
    'FRANCE','BRAZIL','CHINA','INDIA','JAPAN','EGYPT','GHANA','ITALY','SPAIN','CHILE',
    'PERU','CUBA','IRAN','IRAQ','OMAN','FIJI','LAOS','MALI','TOGO','CHAD',
    'BENIN','KENYA','NEPAL','QATAR','SUDAN','SYRIA','LIBYA','HAITI','NAURU',
    'PALAU','TONGA','SAMOA','GREECE','TURKEY','RUSSIA','POLAND','SWEDEN',
    'NORWAY','DENMARK','FINLAND','AUSTRIA','BELGIUM','IRELAND','PORTUGAL','HUNGARY',
    'ROMANIA','UKRAINE','ISRAEL','KUWAIT','BAHRAIN','BHUTAN','MYANMAR',
    'CAMBODIA','VIETNAM','THAILAND','MALAYSIA','INDONESIA','PHILIPPINES',
    'TAIWAN','MONGOLIA','ARMENIA','MOLDOVA','ALBANIA','SERBIA','CROATIA',
    'SLOVENIA','ESTONIA','LATVIA','LITHUANIA','ICELAND','MALTA','CYPRUS',
    'ANDORRA','MALDIVES','SEYCHELLES','MAURITIUS','ERITREA',
    'SOMALIA','RWANDA','BURUNDI','MALAWI','ZAMBIA','ZIMBABWE','BOTSWANA','NAMIBIA',
    'ANGOLA','GABON','CAMEROON','SENEGAL','GUINEA','LIBERIA',
  ],
  planet: [
    'MERCURY','VENUS','EARTH','MARS','JUPITER','SATURN','URANUS','NEPTUNE',
  ],
  number: [
    'ONE','TWO','THREE','FOUR','FIVE','SIX','SEVEN','EIGHT','NINE','TEN',
    'ELEVEN','TWELVE','THIRTEEN','FOURTEEN','FIFTEEN','SIXTEEN','SEVENTEEN',
    'EIGHTEEN','NINETEEN','TWENTY','THIRTY','FORTY','FIFTY','SIXTY','SEVENTY',
    'EIGHTY','NINETY','HUNDRED','THOUSAND','MILLION','BILLION',
  ],
  tree: [
    'OAK','MAPLE','CEDAR','BIRCH','WILLOW','PINE','ASH','ELM',
    'SPRUCE','FIR','YEW','BEECH','ALDER','ASPEN','HOLLY','LIME','HAWTHORN',
    'ROWAN','ELDER','POPLAR','SYCAMORE','LAUREL','MAGNOLIA','CYPRESS',
    'REDWOOD','SEQUOIA','BAMBOO','BAOBAB','BANYAN','EBONY','MAHOGANY','TEAK','BALSA',
    'ACACIA','EUCALYPTUS','JACARANDA','MIMOSA','MYRTLE','LARCH','JUNIPER',
  ],
  gemstone: [
    'RUBY','SAPPHIRE','EMERALD','DIAMOND','OPAL','TOPAZ','GARNET','AMBER','PEARL',
    'JADE','ONYX','QUARTZ','AMETHYST','CITRINE','PERIDOT','TURQUOISE','AQUAMARINE',
    'BERYL','JASPER','AGATE','OBSIDIAN','SPINEL','ZIRCON','CORAL','IVORY','LAPIS',
    'MALACHITE','MOONSTONE','SUNSTONE','TOURMALINE','TANZANITE','ALEXANDRITE',
    'CHRYSOPRASE','RHODONITE','SODALITE','AVENTURINE','CARNELIAN','CHALCEDONY',
  ],
  mythical: [
    'DRAGON','PHOENIX','UNICORN','GRIFFIN','KRAKEN','SPHINX','CENTAUR','CYCLOPS',
    'MEDUSA','HARPY','MINOTAUR','CHIMERA','HYDRA','PEGASUS','BASILISK','MANTICORE',
    'WEREWOLF','VAMPIRE','MERMAID','SIREN','BANSHEE','GOLEM','DJINN','GNOME','FAIRY',
    'PIXIE','SPRITE','NYMPH','SATYR','TITAN','GORGON','LEVIATHAN','RUSALKA','SELKIE',
    'KELPIE','WENDIGO','THUNDERBIRD','QUETZAL',
  ],
  occupation: [
    'DOCTOR','LAWYER','PILOT','CHEF','NURSE','JUDGE','BAKER','MINER','WELDER',
    'TAILOR','FARMER','FISHER','HUNTER','ARCHER','SAILOR','TRADER','WRITER','ARTIST',
    'SINGER','DANCER','ACTOR','COACH','GUARD','DRIVER','PORTER','RANGER','WARDEN',
    'HERALD','SCRIBE','MASON','SMITH','COOPER','TANNER','WEAVER','MILLER','BREWER',
    'POTTER','CARVER','GLAZIER','BARBER','BUTCHER','COBBLER','FARRIER','FLETCHER',
    'THATCHER','CHANDLER','VINTNER','APOTHECARY',
  ],
  genre: [
    'JAZZ','BLUES','SOUL','FUNK','PUNK','METAL','OPERA','DISCO','REGGAE','GOSPEL',
    'TANGO','SAMBA','WALTZ','POLKA','SWING','BEBOP','GRUNGE','TECHNO',
    'HOUSE','TRANCE','AMBIENT','FOLK','COUNTRY','CLASSICAL','BAROQUE','ROMANTIC',
    'MOTOWN','RAGTIME','BLUEGRASS','ROCKABILLY','FLAMENCO','BOSSA','CUMBIA',
    'MERENGUE','CALYPSO','ZYDECO','AFROBEAT','QAWWALI',
  ],
  currency: [
    'DOLLAR','EURO','POUND','YEN','FRANC','PESO','RUBLE','RUPEE','KRONA','DINAR',
    'DIRHAM','SHEKEL','FORINT','ZLOTY','KRONE','BAHT','RINGGIT','DONG','TAKA',
    'KYAT','RIYAL','LIRA','WON','YUAN','RAND','NAIRA','CEDIS','BIRR','SHILLING',
    'PIASTRE','FLORIN','GUILDER','DUCAT','GROAT','DENAR','LEVA','MANAT','TENGE',
  ],

  // ── New single-word categories ────────────────────────────────
  popstar: [
    'AALIYAH','ADELE','ASHANTI','AURORA','BECK','BEYONCE','BJORK','BONO','BRANDY',
    'CHER','CIARA','DIDO','DUFFY','ELVIS','ENYA','FEIST','FERGIE','GRIMES','HALSEY',
    'HOZIER','JEWEL','KELIS','KESHA','KYLIE','LIZZO','LORDE','MADONNA','MAXWELL',
    'MOBY','MONICA','MYA','NORMANI','OMARION','PHARRELL','PINK','PRINCE','RIHANNA',
    'ROBYN','ROSALIA','SADE','SEAL','SELENA','SHAKIRA','SIA','SISQO','SOLANGE',
    'STING','STROMAE','SZA','TINASHE','USHER','WEEKND',
  ],
  rockband: [
    'AEROSMITH','AMERICA','ANTHRAX','BEATLES','BLONDIE','BLUR','BOSTON','CARS',
    'CHICAGO','CLASH','COLDPLAY','CRANBERRIES','CREAM','CREED','CURE','DEFTONES',
    'DEVO','DISTURBED','DOORS','EAGLES','EVANESCENCE','EUROPE','EXTREME','FOALS',
    'FOREIGNER','FUGAZI','GARBAGE','GENESIS','GODSMACK','HEART','HOLE','INCUBUS',
    'INTERPOL','JOURNEY','KASABIAN','KILLERS','KINKS','KISS','KORN','LIVE',
    'MASTODON','MEGADETH','METALLICA','MUSE','NICKELBACK','NIRVANA','OASIS',
    'OFFSPRING','PANTERA','PARAMORE','PAVEMENT','PHISH','PIXIES','PLACEBO',
    'POLICE','PORTISHEAD','PRETENDERS','PRIMUS','PULP','QUEEN','RADIOHEAD',
    'RAMONES','RANCID','RUSH','SANTANA','SCORPIONS','SLAYER','SLIPKNOT',
    'SOUNDGARDEN','STAIND','STROKES','STYX','SUEDE','SUPERGRASS','SURVIVOR',
    'TOOL','WEEZER','WHITESNAKE','WHO','WILCO','YES',
  ],
  usstate: [
    'ALABAMA','ALASKA','ARIZONA','ARKANSAS','CALIFORNIA','COLORADO','CONNECTICUT',
    'DELAWARE','FLORIDA','GEORGIA','HAWAII','IDAHO','ILLINOIS','INDIANA','IOWA',
    'KANSAS','KENTUCKY','LOUISIANA','MAINE','MARYLAND','MASSACHUSETTS','MICHIGAN',
    'MINNESOTA','MISSISSIPPI','MISSOURI','MONTANA','NEBRASKA','NEVADA','OHIO',
    'OKLAHOMA','OREGON','PENNSYLVANIA','TENNESSEE','TEXAS','UTAH','VERMONT',
    'VIRGINIA','WASHINGTON','WISCONSIN','WYOMING',
  ],
  worldcapital: [
    'ABUJA','ACCRA','ALGIERS','AMMAN','AMSTERDAM','ANKARA','ASTANA','ATHENS',
    'BAGHDAD','BAKU','BAMAKO','BANGKOK','BEIRUT','BELGRADE','BERLIN','BERN',
    'BISHKEK','BOGOTA','BRASILIA','BRATISLAVA','BRUSSELS','BUCHAREST','BUDAPEST',
    'CAIRO','CANBERRA','CARACAS','CHISINAU','CONAKRY','COPENHAGEN','DAKAR',
    'DAMASCUS','DHAKA','DOHA','DUBLIN','DUSHANBE','FREETOWN','GABORONE',
    'HANOI','HARARE','HAVANA','HELSINKI','ISLAMABAD','JAKARTA','JERUSALEM','KABUL',
    'KAMPALA','KATHMANDU','KHARTOUM','KIGALI','KINGSTON','KINSHASA','KYIV','LIMA',
    'LISBON','LJUBLJANA','LONDON','LUANDA','LUSAKA','MADRID','MANAGUA',
    'MANILA','MINSK','MOGADISHU','MONTEVIDEO','MOSCOW','MUSCAT','NAIROBI',
    'NASSAU','NICOSIA','OSLO','OTTAWA','PARIS','PRAGUE','PRETORIA','PYONGYANG',
    'QUITO','RABAT','REYKJAVIK','RIGA','RIYADH','ROME','SANTIAGO','SARAJEVO',
    'SEOUL','SKOPJE','SOFIA','STOCKHOLM','SUVA','TALLINN','TASHKENT',
    'TBILISI','TEHRAN','THIMPHU','TIRANA','TOKYO','TRIPOLI','TUNIS','ULAANBAATAR',
    'VADUZ','VALLETTA','VIENNA','VILNIUS','WARSAW','WELLINGTON','WINDHOEK',
    'YEREVAN','ZAGREB',
  ],
  river: [
    'AMAZON','COLUMBIA','CONGO','DANUBE','EUPHRATES','GANGES','HUDSON','INDUS',
    'LENA','LOIRE','MEKONG','NILE','ORINOCO','POTOMAC','RHINE',
    'RHONE','SEINE','THAMES','TIBER','TIGRIS','VOLGA','YANGTZE','ZAMBEZI',
  ],
  president: [
    'ADAMS','ARTHUR','BIDEN','BUCHANAN','BUSH','CARTER','CLEVELAND','CLINTON',
    'COOLIDGE','EISENHOWER','FILLMORE','FORD','GRANT','HARDING',
    'HARRISON','HAYES','HOOVER','JACKSON','JEFFERSON','JOHNSON','KENNEDY',
    'LINCOLN','MADISON','MCKINLEY','MONROE','NIXON','OBAMA','PIERCE','POLK',
    'REAGAN','ROOSEVELT','TAFT','TAYLOR','TRUMAN','TRUMP','TYLER',
    'WILSON',
  ],
  element: [
    'ACTINIUM','ALUMINUM','ANTIMONY','ARGON','ARSENIC','BARIUM','BERYLLIUM',
    'BISMUTH','BORON','BROMINE','CADMIUM','CALCIUM','CARBON','CERIUM','CESIUM',
    'CHLORINE','CHROMIUM','COBALT','COPPER','FLUORINE','FRANCIUM','GADOLINIUM',
    'GALLIUM','GERMANIUM','GOLD','HAFNIUM','HELIUM','HYDROGEN','IODINE','IRIDIUM',
    'IRON','KRYPTON','LANTHANUM','LEAD','LITHIUM','MAGNESIUM','MANGANESE',
    'MOLYBDENUM','NEON','NEPTUNIUM','NICKEL','NIOBIUM','NITROGEN','OSMIUM','OXYGEN',
    'PALLADIUM','PHOSPHORUS','PLATINUM','PLUTONIUM','POLONIUM','POTASSIUM','RADIUM',
    'RADON','RHENIUM','RHODIUM','RUBIDIUM','RUTHENIUM','SELENIUM','SILICON','SILVER',
    'SODIUM','STRONTIUM','SULFUR','TANTALUM','TECHNETIUM','TELLURIUM','THALLIUM',
    'THORIUM','TIN','TITANIUM','TUNGSTEN','URANIUM','VANADIUM','XENON','YTTRIUM',
    'ZINC','ZIRCONIUM',
  ],
  constellation: [
    'ANDROMEDA','AQUARIUS','AQUILA','ARIES','AURIGA','BOOTES','CANCER','CAPRICORNUS',
    'CASSIOPEIA','CENTAURUS','CEPHEUS','CETUS','CORVUS','CYGNUS','DRACO','ERIDANUS',
    'GEMINI','LEO','LEPUS','LIBRA','LYRA','OPHIUCHUS','ORION',
    'PERSEUS','PISCES','SAGITTARIUS','SCORPIUS','SERPENS',
    'TAURUS','VIRGO',
  ],

  // ── New multi-word categories ─────────────────────────────────
  actor: [
    'TOM HANKS','MERYL STREEP','BRAD PITT','JULIA ROBERTS','DENZEL WASHINGTON',
    'CATE BLANCHETT','LEONARDO DICAPRIO','TOM CRUISE','MORGAN FREEMAN',
    'SCARLETT JOHANSSON','MATT DAMON','WILL SMITH','JOHNNY DEPP','NICOLE KIDMAN',
    'KATE WINSLET','HARRISON FORD','ROBERT DE NIRO','AL PACINO','JACK NICHOLSON',
    'SAMUEL L JACKSON','ANGELINA JOLIE','GEORGE CLOONEY','SANDRA BULLOCK',
    'CHARLIZE THERON','HALLE BERRY','EMMA STONE','NATALIE PORTMAN','KEANU REEVES',
    'RYAN GOSLING','DWAYNE JOHNSON','JENNIFER LAWRENCE','EMMA WATSON',
    'ROBERT DOWNEY JR','CHRIS HEMSWORTH','CHRIS EVANS','CHRIS PRATT','ZENDAYA',
    'TIMOTHEE CHALAMET','MARGOT ROBBIE','VIOLA DAVIS','LUPITA NYONGO',
    'ANNE HATHAWAY','REESE WITHERSPOON','IDRIS ELBA','JOAQUIN PHOENIX',
    'CHRISTIAN BALE','MICHELLE YEOH','PENELOPE CRUZ','HUGH JACKMAN','DANIEL CRAIG',
    'GAL GADOT','BEN AFFLECK','LIAM NEESON','DUSTIN HOFFMAN','ROBIN WILLIAMS',
    'CLINT EASTWOOD','SYLVESTER STALLONE','MEL GIBSON','BRUCE WILLIS',
    'RUSSELL CROWE','JODIE FOSTER','DIANE KEATON','SIGOURNEY WEAVER','GLENN CLOSE',
    'SEAN CONNERY','MICHAEL CAINE','ANTHONY HOPKINS','JUDI DENCH','HELEN MIRREN',
    'JANE FONDA','JOHN WAYNE','JAMES STEWART','HUMPHREY BOGART','MARLON BRANDO',
    'ELIZABETH TAYLOR','AUDREY HEPBURN','MARILYN MONROE','PAUL NEWMAN',
    'ROBERT REDFORD','STEVE MCQUEEN','JAMES DEAN','GARY COOPER','CLARK GABLE',
    'BETTE DAVIS','KATHARINE HEPBURN','INGRID BERGMAN','GENE KELLY','FRED ASTAIRE',
    'GRETA GARBO','VIVIEN LEIGH','GREGORY PECK','KIRK DOUGLAS','SIDNEY POITIER',
    'PETER SELLERS','PETER OTOOLE','SOPHIA LOREN','BRIGITTE BARDOT','CARY GRANT',
    'BRUCE LEE','JACKIE CHAN',
  ],
  athlete: [
    'PELE','LIONEL MESSI','CRISTIANO RONALDO','RONALDO','NEYMAR','RONALDINHO',
    'DIEGO MARADONA','ZINEDINE ZIDANE','DAVID BECKHAM','THIERRY HENRY',
    'JOHAN CRUYFF','KYLIAN MBAPPE','WAYNE ROONEY','GARETH BALE','ERLING HAALAND',
    'ZLATAN IBRAHIMOVIC','MICHAEL JORDAN','LEBRON JAMES','KOBE BRYANT',
    'SHAQUILLE ONEAL','MAGIC JOHNSON','STEPHEN CURRY','KEVIN DURANT',
    'SERENA WILLIAMS','ROGER FEDERER','RAFAEL NADAL','NOVAK DJOKOVIC',
    'VENUS WILLIAMS','MARIA SHARAPOVA','STEFFI GRAF','BJORN BORG','JOHN MCENROE',
    'BILLIE JEAN KING','PETE SAMPRAS','ANDRE AGASSI','BORIS BECKER','NAOMI OSAKA',
    'ANDY MURRAY','TIGER WOODS','JACK NICKLAUS','ARNOLD PALMER','GARY PLAYER',
    'MUHAMMAD ALI','MIKE TYSON','FLOYD MAYWEATHER','MANNY PACQUIAO','LENNOX LEWIS',
    'SUGAR RAY LEONARD','GEORGE FOREMAN','USAIN BOLT','CARL LEWIS','JESSE OWENS',
    'MICHAEL JOHNSON','ELIUD KIPCHOGE','MO FARAH','MICHAEL PHELPS','KATIE LEDECKY',
    'BABE RUTH','MICHAEL SCHUMACHER','LEWIS HAMILTON','AYRTON SENNA',
    'MAX VERSTAPPEN','LANCE ARMSTRONG','NADIA COMANECI','SIMONE BILES',
    'CONOR MCGREGOR','RONDA ROUSEY','TONY HAWK',
  ],
  landmark: [
    'EIFFEL TOWER','BIG BEN','STONEHENGE','COLOSSEUM','PARTHENON','ACROPOLIS',
    'TOWER OF LONDON','LEANING TOWER','NOTRE DAME','VERSAILLES','ALHAMBRA',
    'KREMLIN','RED SQUARE','POMPEII','BUCKINGHAM PALACE','WESTMINSTER ABBEY',
    'TOWER BRIDGE','MATTERHORN','BERLIN WALL','SISTINE CHAPEL','BRANDENBURG GATE',
    'MOUNT VESUVIUS','TREVI FOUNTAIN','ARC DE TRIOMPHE','LA SAGRADA FAMILIA',
    'TAJ MAHAL','GREAT WALL','MOUNT FUJI','MOUNT EVEREST','ANGKOR WAT','PETRA',
    'FORBIDDEN CITY','TERRACOTTA ARMY','DEAD SEA','BURJ KHALIFA','HAGIA SOPHIA',
    'WAILING WALL','PYRAMIDS OF GIZA','GREAT SPHINX','SAHARA DESERT',
    'VICTORIA FALLS','MOUNT KILIMANJARO','TABLE MOUNTAIN','CAPE OF GOOD HOPE',
    'SERENGETI','NIAGARA FALLS','GRAND CANYON','STATUE OF LIBERTY',
    'GOLDEN GATE BRIDGE','MOUNT RUSHMORE','HOLLYWOOD SIGN','YELLOWSTONE',
    'CHICHEN ITZA','MACHU PICCHU','EASTER ISLAND','GALAPAGOS ISLANDS',
    'IGUAZU FALLS','ANGEL FALLS','ULURU','SYDNEY OPERA HOUSE','GREAT BARRIER REEF',
    'NORTHERN LIGHTS','SUEZ CANAL','PANAMA CANAL',
  ],
  fictional: [
    'BATMAN','SUPERMAN','SPIDER MAN','WONDER WOMAN','IRON MAN','CAPTAIN AMERICA',
    'HULK','THOR','WOLVERINE','JOKER','TINTIN','ASTERIX','CINDERELLA','SNOW WHITE',
    'SLEEPING BEAUTY','RAPUNZEL','GOLDILOCKS','HUMPTY DUMPTY','PINOCCHIO','ALICE',
    'DOROTHY','PETER PAN','MARY POPPINS','PETER RABBIT','PADDINGTON','WILLY WONKA',
    'WINNIE THE POOH','TINKER BELL','CAPTAIN HOOK','ROMEO','JULIET','HAMLET',
    'MACBETH','ZEUS','ACHILLES','ODYSSEUS','KING ARTHUR',
    'MERLIN','ROBIN HOOD','SANTA CLAUS','SHERLOCK HOLMES','DRACULA','FRANKENSTEIN',
    'DON QUIXOTE','HUCKLEBERRY FINN','TOM SAWYER','OLIVER TWIST','ROBINSON CRUSOE',
    'MOBY DICK','SCARLETT OHARA','TARZAN','ZORRO','JAMES BOND','INDIANA JONES',
    'KING KONG','GODZILLA','DARTH VADER','LUKE SKYWALKER','PRINCESS LEIA','YODA',
    'JACK SPARROW','ROCKY BALBOA','RAMBO','TERMINATOR','HANNIBAL LECTER',
    'FORREST GUMP','CAPTAIN KIRK','SPOCK','HOMER SIMPSON','MICKEY MOUSE',
    'DONALD DUCK','BUGS BUNNY','SCOOBY DOO','POPEYE','SNOOPY',
    'CHARLIE BROWN','HARRY POTTER','FRODO','GANDALF','VOLDEMORT','DUMBLEDORE',
    'SHREK','ALADDIN','SIMBA','BUZZ LIGHTYEAR','BAMBI','BARBIE','MARIO','PIKACHU',
  ],
};

// Build category map — works for single and multi-word entries
const CATEGORY_MAP = {};
Object.entries(CATEGORY_POOL).forEach(([cat, words]) => {
  words.forEach(w => { CATEGORY_MAP[w] = cat; });
});

// ── Distractor pool ───────────────────────────────────────────────
// Hard-false words chosen to feel plausible for each rule.
// Every entry has been verified: not in any category pool, actually fails its rule.
// Multi-word entries only appear for multi-word-friendly category rules.
const DISTRACTOR_POOL = {
  // VOWEL rules — no Y-containing words
  S01: ['QUEUE','AUDIO','IDEA','AREA','IOTA','OBOE','AIDE','OCEAN','OZONE'],
  S02: ['STRENGTH','SHRUNK','SCRAWL','BRUNT','BRANCH','SCRIPT'],
  S06: ['OCEAN','ALIEN','AUDIO','UNITED','MAIDEN','COINED','OBLIGE','LADIES'],
  S24: ['HOUR','HEIR','HONEST','HONOR','HERB','HUMBLE'],        // silent H — feel like vowel starts
  S25: ['FLOW','SHOW','BELOW','SHADOW','HOLLOW','NARROW','MEADOW','FOLLOW'], // end in W, sound like vowel
  S28: ['EQUATION','BEAUTIFUL','EVACUATE','ASSOCIATE','AQUEOUS'], // 4-5 vowels, look like 3
  S53: ['QUEUE','LEAGUE','UNIQUE','OPAQUE','SEQUEL','SEQUIN','EQUINE','QUICHE'], // look like 2, aren't

  // PATTERN rules
  S03: ['REGAL','REPOT','STRAW','MINED','STRAP','SPORT','DEPOT'],  // near-palindromes, almost same start/end
  S04: ['SPEED','TEETH','SLEEP','BOOTH','PROOF','BLOOD','MOON','DEEP','WOOL'], // hidden doubles
  S11: ['BEACH','REACH','TEACH','ROACH','LUNCH','BUNCH','HUNCH','MUCH',       // CH/SH mimics doubling
        'SUCH','RICH','EACH','ARCH','TORCH','MARCH','PORCH','PERCH'],

  // LANGUAGE rules
  S05: ['BLANK','FLASK','BLEND','PLANK','FRANK'],               // look like they hide a silent letter
  S13: ['BLANK','CLAMP','FLANK','FRANK','CLOAK','BLOCK',        // contain letters N-Z players miss
        'BRAND','CRAMP','NOUN','PLANK'],
  S14: ['REGAL','REPOT','STRAW','STRAP','SPORT','RESIN','REMIX'], // near-palindromes
  S31: ['SPORT','STORY','STRAP','SCORE','BLEND','PLANT','STONE', // look alphabetical, aren't
        'DRIVE','BREAK','FRAME','GRIND','PLACE','PLAIN','PRICE',
        'PRONE','PROSE','TRADE','TRACE','TRIBE','TRICK','SPADE'],
  S54: ['STONE','STRIPE','THRONE','SCENE','BLADE','GRACE',       // start consonant, end silent E
        'PRIME','CRUDE','BRAKE','FRAME'],
  S56: ['CARPET','BASKET','WALLET','BUTTON','MARKET','CORNER',   // feel compound, aren't
        'WINTER','BLANKET','PLANET','HELMET','JACKET','RACKET',
        'BONNET','BUCKET','TABLET','MAGNET','GOBLET','LANTERN',
        'MASTER','GARDEN','TENDER'],
  S57: ['STRENGTH','THROUGH','THOUGHT','STRAIGHT','GLIMPSE',     // 1 syllable, look polysyllabic
        'SCHEME','CLOTHES','SPRAWL','SQUELCH','BRUISED','CLEANSE',
        'BREATHE','LAUNCH','BROUGHT','WOLVES','THRONE','TWELFTH',
        'SCORCHED','DRENCHED','STRETCHED','WRENCHED'],

  // WORLD rules — knowledge-based plausible near-misses
  S15: ['FERAL','WILD','BEAST','PREY','HERD','VEAL','MARE','FOAL','BROOD','SPAWN','FLOCK'],
  S16: ['BRIGHT','VIVID','PALE','PASTEL','MUTED','BOLD','LIGHT','DARK','RICH'],
  S17: ['HIKING','FISHING','DANCING','YOGA','CHESS','SPRINT','DUEL','HUNT','CHASE','JOGGING'],
  S18: ['ENGINE','TURBINE','RUDDER','ANCHOR','HULL','MAST','PROPELLER','CHASSIS','ESCALATOR'],
  S19: ['RECIPE','CUISINE','FLAVOR','SAUCE','GRAVY','YEAST','PETAL','BARK','RESIN','SAP'],
  S20: ['MELODY','RHYTHM','TEMPO','CHORD','SCALE','VERSE','CHORUS','TREBLE','BRIDGE','REFRAIN'],
  S21: ['SEASON','CLIMATE','FORECAST','COLD','HOT','WARM','COOL','DUST','SMOKE','POLAR'],
  S22: ['ATTITUDE','TEMPER','MOOD','SPIRIT','NATURE','VIBE','STRESS','TRAUMA','TENSION'],
  S23: ['VEIN','NERVE','CELL','TISSUE','GLAND','PORE','TENDON','MARROW'],
  S29: ['TIBET','KASHMIR','SIBERIA','CATALONIA','CORNWALL',      // regions that feel like countries
        'BRITTANY','TUSCANY','PATAGONIA','ANATOLIA','CRIMEA','YORKSHIRE','ALSACE'],
  S30: ['COMET','METEOR','NEBULA','PULSAR','QUASAR','ECLIPSE',   // space objects, not planets
        'EUROPA','TRITON','COSMOS','ORBIT','SOLSTICE','EQUINOX'], // moons + space terms
  S32: ['DOZEN','SCORE','GROSS','HALF','QUARTER','TRIPLE',       // quantitative but not number words
        'DOUBLE','PRIME','DIGIT','ONCE','TWICE'],
  S35: ['FERN','SHRUB','CACTUS','THISTLE','CLOVER','HEATHER','HEMP','REED','VINE','MOSS','WEED'],
  S36: ['CHROME','CRYSTAL','MARBLE','GRANITE','STEEL','GLASS'],  // shiny/precious, not gemstones
  S37: ['BEAST','FIEND','GOBLIN','ALIEN','BIGFOOT','YETI','SERPENT','DEMON','MONSTER','SPECTER'],
  S38: ['CAPTAIN','MASTER','LEADER','ROOKIE','VETERAN','NOVICE','EXPERT','CHIEF','BOSS'],
  S39: ['MELODY','TEMPO','RHYTHM','CHORD','BALLAD','ANTHEM','VERSE','CHORUS','REFRAIN','BRIDGE'],
  S40: ['STOCK','BOND','COIN','CASH','CREDIT','TOKEN','BULLION','LEDGER','VAULT'],
  S41: ['BOWIE','LENNON','JAGGER','COBAIN','HENDRIX','PRESLEY','SINATRA','MORRISON','CLAPTON'],
  S42: ['STATIC','VOLTAGE','CHAOS','SHADOW','BOWIE','LENNON','JAGGER'],
  S43: ['DAKOTA','CAROLINA','PORTLAND','RICHMOND','TERRITORY','DISTRICT','PROVINCE'],
  S44: ['SYDNEY','TORONTO','ISTANBUL','MILAN','LAGOS','KARACHI','SHANGHAI','BARCELONA','MELBOURNE'],
  S45: ['LAKE','DELTA','CANYON','GORGE','FJORD','STRAIT','GULF','RAPIDS','ESTUARY','LAGOON'],
  S46: ['HAMILTON','BURR','CLAY','DEWEY','WEBSTER','CALHOUN',    // almost-presidents
        'GORE','KERRY','FRANKLIN','EDISON','ARMSTRONG','COLUMBUS','ROCKEFELLER','CARNEGIE'],
  S47: ['ACID','ALLOY','ISOTOPE','PLASMA','COMPOUND','CRYSTAL','PROTON','NEUTRON','ELECTRON'],
  S48: ['NEBULA','GALAXY','NOVA','COMET','PULSAR','QUASAR',      // space terms, not constellations
        'COSMOS','ECLIPSE','METEOR','SOLSTICE','EQUINOX','ZENITH','NADIR'],

  // CULTURE rules — multi-word distractors included
  S49: ['WINSTON CHURCHILL','NAPOLEON BONAPARTE','JULIUS CAESAR','ALBERT EINSTEIN',
        'CHARLES DARWIN','SIGMUND FREUD','PABLO PICASSO','VINCENT VAN GOGH',
        'MICHAEL JACKSON','ELVIS PRESLEY','KURT COBAIN','FREDDIE MERCURY'],
  S50: ['NAPOLEON BONAPARTE','JULIUS CAESAR','ALEXANDER THE GREAT','GENGHIS KHAN',
        'WINSTON CHURCHILL','ALBERT EINSTEIN','NIKOLA TESLA','NEIL ARMSTRONG',
        'AMELIA EARHART','CHARLES DARWIN'],
  S51: ['AMAZON RIVER','ARCTIC OCEAN','PACIFIC OCEAN','ATLANTIC OCEAN',
        'MEDITERRANEAN SEA','MOUNT OLYMPUS','ISLE OF SKYE','LAKE VICTORIA','LAKE TITICACA'],
  S52: ['KING HENRY','QUEEN VICTORIA','NAPOLEON','CLEOPATRA','JULIUS CAESAR',
        'ALEXANDER HAMILTON','WILLIAM SHAKESPEARE','NIKOLA TESLA','ALBERT EINSTEIN',
        'CHARLES DARWIN','ABRAHAM LINCOLN'],
};

// Categories containing multi-word entries — never used in computational rule pools
const MULTIWORD_CATS = new Set(['actor','athlete','landmark','fictional']);
function isMultiWord(w) { return w.includes(' '); }

// ── General word pool for computational rules ─────────────────────
const GENERAL_WORDS = [
  'ARCH','BARN','DARK','FARM','GLOW','HELM','JEST','KITE','LOFT','NORM','RAFT',
  'SALT','VALE','WAND','BIRD','DRUM','GUST','HULL','LURE','PYRE','RUST','TUFT',
  'VEST','YARN','ZONE','BROW','CREW','DUSK','GRIM','HINT','JOLT','KELP','MUSE',
  'NOOK','BARD','HOWL','JINX','LURK','RUSE','SULK','URGE','VAST','WILT','YELP',
  'ZEAL','CRAG','DEFT','FLAX','GLIB','HUSK','KNOB','LILT','MOOT','OPAL','PIXY',
  'BLAND','BLEND','BRICK','CHARM','CHEST','CLAMP','CRAFT','CRANK','CREST','DRAWL',
  'DRIFT','DRILL','FLASK','FLEET','FLESH','FLOCK','FORGE','FRANK','FRESH','GLARE',
  'GLINT','GLOOM','GRASP','GRAZE','GREED','GRIND','GROAN','GROVE','GROWL','GRUNT',
  'HASTE','HEART','HOARD','HOIST','LATCH','LODGE','MARCH','MATCH','MERIT','MIRTH',
  'MOIST','MORAL','MULCH','NOBLE','NOTCH','PATCH','PEARL','PERCH','PHASE','PILOT',
  'PINCH','PIVOT','PLANK','PLEAT','PLUCK','PLUME','PLUSH','PORCH','POUND','PRANK',
  'PRESS','PRIME','PRISM','PROOF','PROWL','PRUNE','PUNCH','PURGE','QUEST','QUIRK',
  'RANCH','RAPID','REACH','REALM','REBEL','ROUGH','SALVO','SCALD','SCANT','SCARF',
  'SCENT','SCOUT','SCOWL','SCRAP','SHAFT','SHAKE','SHAME','SHARP','SHAWL','SHIFT',
  'SHOCK','SHORE','SHORT','SHOUT','SHOVE','SHRUG','SKIMP','SLANT','SLASH','SLEEK',
  'SLICK','SLIDE','SLING','SLOPE','SLUMP','SMASH','SMEAR','SMILE','SMIRK','SMOKE',
  'SNARE','SNARL','SNEAK','SNIFF','SNORE','SNORT','SPARE','SPARK','SPAWN','SPECK',
  'SPELL','SPEND','SPILL','SPINE','SPITE','SPLIT','SPORT','SPRAY','STACK','STAIN',
  'STALE','STALK','STALL','STAMP','STARE','STARK','STEAL','STEEP','STEER','STERN',
  'STICK','STIFF','STING','STOMP','STONE','STRAP','STRAW','STRAY','STRIP','STRUT',
  'STUMP','STUNT','STYLE','SURGE','SWAMP','SWARM','SWEAR','SWEAT','SWEEP','SWING',
  'SWIRL','SWOOP','THORN','TOUCH','TOUGH','TRACE','TRACK','TRAIL','TRASH','TRAWL',
  'TREAD','TREND','TRICK','TRILL','TROOP','TROVE','TRUCK','TRYST','TWIST','VOUCH',
  'WRATH','WRECK','YAWNS','PLAID','CLAIM','CLOAK','CRAWL','CREEK','CROWN','CRUMB',
  'CRUSH','CRUST','DRAPE','DREAD','DRINK','DROOL','DROOP','FLAIR','FLAME','FLANK',
  'FLAP','FLASH','FLECK','FLING','FLINT','FLOAT','FLOCK','FLOOD','FLOOR',
  'FLOSS','FRAIL','FRAME','FRAUD','FREAK','FREED','FROND','FROST','FROZE','FROWN',
  'BRAID','BRAIN','BRAKE','BRAND','BRAVE','BRAWL','BRAWN','BRAZE','BROIL','BROKE',
  'BROOD','BROOK','BROTH','BROWN','CLACK','CLANG','CLANK','CLASH','CLASP',
  'CLASS','CAULK','GRUFF','PLUMB','SCAMP','SCALP','SCRAM','SCRUB','SHEEN','SHOAL',
  'SLEET','SLINK','SMOCK','SMUDGE','SNACK','SNAIL','SNOOP','SPIRE',
  'STAND','STOUT','SWATH','THATCH','THICK',
  'THROB','THROW','THRUM','THUD','THUMB','THUMP','TINGE','TIPSY','TORCH',
  'TOXIC','TRAMP','TRUCE','TRUMP','TRUNK','TRUSS','TUBER','TULIP',
  'VAULT','VIGOR','VISOR','VOGUE','WHELP','WHIFF','WHIRL','WHISK',
  'CLEFT','CLUNK','CRIMP','DENSE','DEPOT',
  'CRYPT','DEPTH','DERBY','DISCO','DITCH',
  'DWARF','EJECT','EPOCH','EVOKE','EXERT','EXTOL','EXULT',
  'FABLE','FACET','FAKER','FANCY','FARCE','FAULT','FEAST','FETID',
  'FIEND','FILCH','FJORD','FLOUT','FORAY',
  'FRISK','FROTH','FUNGI','GAMUT','GAUZE','GAVEL','GELID',
  'GHOUL','GLAIR','GLEAN','GLIDE','GLOAT',
  'GLOSS','GLYPH','GNASH','GNOME','GOUGE','GRAFT',
  'GRAIL','GRIPE','GROIN','GROUP','GROUT','GUILD','GUILE','GUISE','GULCH',
  'SYNOD','TAINT','TALON','TAUNT','TEPID','TERSE',
  'SHUNT','SCULPT','SCUFF','SCHWA','SAVOR','SNIDE',
  'STOIC','STOKE','STONY','SNOUT','SMELT','SMOTE',
  'BRISK','GRUEL','GUSTO','INEPT',
  'INSET','INTER','INTRO','IRATE','ISLET','JOUST','KNAVE','KNEEL','KNELT',
];

// ── Vowel rule IDs ────────────────────────────────────────────────
const VOWEL_RULE_IDS = new Set(['S01','S02','S06','S24','S25','S28','S53']);

// ── Rule definitions ──────────────────────────────────────────────
const SINGLE_RULES = [
  // VOWEL / STRUCTURAL
  { id:'S01', label:'Has more consonants than vowels',      family:'VOWEL',    supergroup:'STRUCTURAL', check: w => { const v=(w.match(/[AEIOU]/g)||[]).length; return (w.length-v)>v; } },
  { id:'S02', label:'Has more vowels than consonants',      family:'VOWEL',    supergroup:'STRUCTURAL', check: w => { const v=(w.match(/[AEIOU]/g)||[]).length; return v>(w.length-v); } },
  { id:'S06', label:'All vowels in the word are the same', family:'VOWEL',    supergroup:'STRUCTURAL', check: w => { const v=w.match(/[AEIOU]/g); return !!(v&&v.length>0&&new Set(v).size===1); } },
  { id:'S24', label:'Starts with a vowel',                  family:'VOWEL',    supergroup:'STRUCTURAL', check: w => /^[AEIOU]/.test(w) },
  { id:'S25', label:'Ends with a vowel',                    family:'VOWEL',    supergroup:'STRUCTURAL', check: w => /[AEIOU]$/.test(w) },
  { id:'S28', label:'Contains exactly 3 vowels',            family:'VOWEL',    supergroup:'STRUCTURAL', check: w => (w.match(/[AEIOU]/g)||[]).length===3 },
  { id:'S53', label:'Contains exactly 2 vowels',            family:'VOWEL',    supergroup:'STRUCTURAL', check: w => (w.match(/[AEIOU]/g)||[]).length===2 },
  // SHAPE / STRUCTURAL
  { id:'S07', label:'Is exactly 4 letters long',            family:'SHAPE',    supergroup:'STRUCTURAL', check: w => w.replace(/ /g,'').length===4 },
  { id:'S08', label:'Is exactly 5 letters long',            family:'SHAPE',    supergroup:'STRUCTURAL', check: w => w.replace(/ /g,'').length===5 },
  { id:'S09', label:'Is exactly 6 letters long',            family:'SHAPE',    supergroup:'STRUCTURAL', check: w => w.replace(/ /g,'').length===6 },
  { id:'S10', label:'Is more than 6 letters long',          family:'SHAPE',    supergroup:'STRUCTURAL', check: w => w.replace(/ /g,'').length>6 },
  // PATTERN / STRUCTURAL
  { id:'S03', label:'Starts and ends with the same letter', family:'PATTERN',  supergroup:'STRUCTURAL', check: w => w.length>1 && w[0]===w[w.length-1] },
  { id:'S04', label:'Contains no repeated letters',         family:'PATTERN',  supergroup:'STRUCTURAL', check: w => { const s=w.replace(/ /g,''); return new Set(s).size===s.length; } },
  { id:'S11', label:'Contains a double letter',             family:'PATTERN',  supergroup:'STRUCTURAL', check: w => /(.)\1/.test(w) },
  { id:'S26', label:'Contains the letter S',                family:'PATTERN',  supergroup:'STRUCTURAL', check: w => w.includes('S') },
  { id:'S27', label:'Contains the letter R',                family:'PATTERN',  supergroup:'STRUCTURAL', check: w => w.includes('R') },
  { id:'S33', label:'Contains the letter T',                family:'PATTERN',  supergroup:'STRUCTURAL', check: w => w.includes('T') },
  { id:'S34', label:'Contains the letter N',                family:'PATTERN',  supergroup:'STRUCTURAL', check: w => w.includes('N') },
  // LANGUAGE / STRUCTURAL
  { id:'S05', label:'Contains a silent letter',             family:'LANGUAGE', supergroup:'STRUCTURAL', check: w => SILENT_SET.has(w) },
  { id:'S13', label:'All letters are in the first half of the alphabet', family:'LANGUAGE', supergroup:'STRUCTURAL', check: w => { const s=w.replace(/ /g,''); return [...s].every(c=>c>='A'&&c<='M'); } },
  { id:'S14', label:'Is a palindrome',                      family:'LANGUAGE', supergroup:'STRUCTURAL', check: w => w.length>1 && w===w.split('').reverse().join('') },
  { id:'S31', label:'Letters are in alphabetical order',    family:'LANGUAGE', supergroup:'STRUCTURAL', check: w => { const s=w.replace(/ /g,''); const a=[...s]; return a.every((c,i)=>i===0||c>=a[i-1]); } },
  { id:'S54', label:'Starts and ends with a consonant',     family:'LANGUAGE', supergroup:'STRUCTURAL', check: w => !/^[AEIOU]/.test(w) && !/[AEIOU]$/.test(w) },
  { id:'S55', label:'Contains the letter Z',                family:'LANGUAGE', supergroup:'STRUCTURAL', check: w => w.includes('Z') },
  { id:'S56', label:'Is a compound word',                   family:'LANGUAGE', supergroup:'STRUCTURAL', check: w => COMPOUND_SET.has(w) },
  { id:'S57', label:'Contains 3 or more syllables',         family:'LANGUAGE', supergroup:'STRUCTURAL', check: w => SYLLABLE_SET.has(w) },
  // WORLD / KNOWLEDGE
  { id:'S15', label:'Is an animal',                family:'WORLD', supergroup:'KNOWLEDGE', check: w => CATEGORY_MAP[w]==='animal' },
  { id:'S16', label:'Is a color',                 family:'WORLD', supergroup:'KNOWLEDGE', check: w => CATEGORY_MAP[w]==='color' },
  { id:'S17', label:'Is a sport',                 family:'WORLD', supergroup:'KNOWLEDGE', check: w => CATEGORY_MAP[w]==='sport' },
  { id:'S18', label:'Is a vehicle',               family:'WORLD', supergroup:'KNOWLEDGE', check: w => CATEGORY_MAP[w]==='vehicle' },
  { id:'S19', label:'Is a food or ingredient',    family:'WORLD', supergroup:'KNOWLEDGE', check: w => CATEGORY_MAP[w]==='food' },
  { id:'S20', label:'Is a musical instrument',    family:'WORLD', supergroup:'KNOWLEDGE', check: w => CATEGORY_MAP[w]==='instrument' },
  { id:'S21', label:'Is a weather word',          family:'WORLD', supergroup:'KNOWLEDGE', check: w => CATEGORY_MAP[w]==='weather' },
  { id:'S22', label:'Is an emotion',              family:'WORLD', supergroup:'KNOWLEDGE', check: w => CATEGORY_MAP[w]==='emotion' },
  { id:'S23', label:'Is a body part',             family:'WORLD', supergroup:'KNOWLEDGE', check: w => CATEGORY_MAP[w]==='body' },
  { id:'S29', label:'Is a country',               family:'WORLD', supergroup:'KNOWLEDGE', check: w => CATEGORY_MAP[w]==='country' },
  { id:'S30', label:'Is a planet',                family:'WORLD', supergroup:'KNOWLEDGE', check: w => CATEGORY_MAP[w]==='planet' },
  { id:'S32', label:'Is a number word',           family:'WORLD', supergroup:'KNOWLEDGE', check: w => CATEGORY_MAP[w]==='number' },
  { id:'S35', label:'Is a tree',                  family:'WORLD', supergroup:'KNOWLEDGE', check: w => CATEGORY_MAP[w]==='tree' },
  { id:'S36', label:'Is a gemstone',              family:'WORLD', supergroup:'KNOWLEDGE', check: w => CATEGORY_MAP[w]==='gemstone' },
  { id:'S37', label:'Is a mythical creature',     family:'WORLD', supergroup:'KNOWLEDGE', check: w => CATEGORY_MAP[w]==='mythical' },
  { id:'S38', label:'Is an occupation',           family:'WORLD', supergroup:'KNOWLEDGE', check: w => CATEGORY_MAP[w]==='occupation' },
  { id:'S39', label:'Is a music genre',           family:'WORLD', supergroup:'KNOWLEDGE', check: w => CATEGORY_MAP[w]==='genre' },
  { id:'S40', label:'Is a currency',              family:'WORLD', supergroup:'KNOWLEDGE', check: w => CATEGORY_MAP[w]==='currency' },
  { id:'S43', label:'Is a US state',              family:'WORLD', supergroup:'KNOWLEDGE', check: w => CATEGORY_MAP[w]==='usstate' },
  { id:'S44', label:'Is a world capital',         family:'WORLD', supergroup:'KNOWLEDGE', check: w => CATEGORY_MAP[w]==='worldcapital' },
  { id:'S45', label:'Is a famous river',          family:'WORLD', supergroup:'KNOWLEDGE', check: w => CATEGORY_MAP[w]==='river' },
  { id:'S47', label:'Is a chemical element',      family:'WORLD', supergroup:'KNOWLEDGE', check: w => CATEGORY_MAP[w]==='element' },
  { id:'S48', label:'Is a constellation',         family:'WORLD', supergroup:'KNOWLEDGE', check: w => CATEGORY_MAP[w]==='constellation' },
  // CULTURE / KNOWLEDGE
  { id:'S41', label:'Is a famous pop star',               family:'CULTURE', supergroup:'KNOWLEDGE', check: w => CATEGORY_MAP[w]==='popstar' },
  { id:'S42', label:'Is a famous rock band',              family:'CULTURE', supergroup:'KNOWLEDGE', check: w => CATEGORY_MAP[w]==='rockband' },
  { id:'S46', label:'Is a US president',                  family:'CULTURE', supergroup:'KNOWLEDGE', check: w => CATEGORY_MAP[w]==='president' },
  // r1Only: true — multi-word pools can't be used in R3 mixed phases (pairs need single words)
  { id:'S49', label:'Is a famous actor or actress',       family:'CULTURE', supergroup:'KNOWLEDGE', r1Only:true, check: w => CATEGORY_MAP[w]==='actor' },
  { id:'S50', label:'Is a famous athlete',                family:'CULTURE', supergroup:'KNOWLEDGE', r1Only:true, check: w => CATEGORY_MAP[w]==='athlete' },
  { id:'S51', label:'Is a famous world landmark',         family:'CULTURE', supergroup:'KNOWLEDGE', r1Only:true, check: w => CATEGORY_MAP[w]==='landmark' },
  { id:'S52', label:'Is a famous fictional character',    family:'CULTURE', supergroup:'KNOWLEDGE', r1Only:true, check: w => CATEGORY_MAP[w]==='fictional' },
];

const PAIR_RULES = [
  { id:'P01', label:'Both words start with the same letter', family:'PATTERN', supergroup:'STRUCTURAL', check:(l,r)=>l[0]===r[0] },
  { id:'P02', label:'Both words end with the same letter',   family:'PATTERN', supergroup:'STRUCTURAL', check:(l,r)=>l[l.length-1]===r[r.length-1] },
  { id:'P03', label:'Both words belong to the same category',family:'WORLD',   supergroup:'KNOWLEDGE',  check:(l,r)=>{ const cl=CATEGORY_MAP[l],cr=CATEGORY_MAP[r]; return !!(cl&&cr&&cl===cr); } },
  { id:'P04', label:'Both words are the same length',        family:'SHAPE',   supergroup:'STRUCTURAL', check:(l,r)=>l.length===r.length },
  { id:'P05', label:'Both words contain a double letter',    family:'PATTERN', supergroup:'STRUCTURAL', check:(l,r)=>/(.)\1/.test(l)&&/(.)\1/.test(r) },
  { id:'P06', label:'Combined letter count is more than 10', family:'SHAPE',   supergroup:'STRUCTURAL', check:(l,r)=>(l.length+r.length)>10 },
  { id:'P07', label:'Both words have more than 5 letters',   family:'SHAPE',   supergroup:'STRUCTURAL', check:(l,r)=>l.length>5&&r.length>5 },
  { id:'P08', label:'Both words start with a consonant',     family:'PATTERN', supergroup:'STRUCTURAL', check:(l,r)=>!/^[AEIOU]/.test(l)&&!/^[AEIOU]/.test(r) },
  { id:'P09', label:'Both words are animals',                family:'WORLD',   supergroup:'KNOWLEDGE',  check:(l,r)=>CATEGORY_MAP[l]==='animal'&&CATEGORY_MAP[r]==='animal' },
  { id:'P10', label:'Both words are colors',                 family:'WORLD',   supergroup:'KNOWLEDGE',  check:(l,r)=>CATEGORY_MAP[l]==='color'&&CATEGORY_MAP[r]==='color' },
  { id:'P11', label:'Both words end with a vowel',           family:'VOWEL',   supergroup:'STRUCTURAL', check:(l,r)=>/[AEIOU]$/.test(l)&&/[AEIOU]$/.test(r) },
  { id:'P12', label:'Both words have the same number of vowels', family:'VOWEL', supergroup:'STRUCTURAL', check:(l,r)=>(l.match(/[AEIOU]/g)||[]).length===(r.match(/[AEIOU]/g)||[]).length },
];

// ── Family adjacency ──────────────────────────────────────────────
const ADJACENT_FAMILIES = {
  PATTERN:  new Set(['PATTERN','SHAPE','VOWEL','LANGUAGE']),
  SHAPE:    new Set(['SHAPE','PATTERN','VOWEL','LANGUAGE']),
  VOWEL:    new Set(['VOWEL','PATTERN','SHAPE','LANGUAGE']),
  LANGUAGE: new Set(['LANGUAGE','PATTERN','SHAPE','VOWEL']),
  WORLD:    new Set(['WORLD','CULTURE']),
  CULTURE:  new Set(['CULTURE','WORLD']),
};

// ── Category rule IDs (for false pool logic) ──────────────────────
const CAT_RULE_IDS = new Set([
  'S15','S16','S17','S18','S19','S20','S21','S22','S23','S29','S30',
  'S32','S35','S36','S37','S38','S39','S40','S41','S42','S43','S44',
  'S45','S46','S47','S48','S49','S50','S51','S52',
]);

// ══════════════════════════════════════════════════════════════════
// Pool builders
// ══════════════════════════════════════════════════════════════════
function getPoolForRule(rule) {
  const catMap = {
    'S15':'animal','S16':'color','S17':'sport','S18':'vehicle','S19':'food',
    'S20':'instrument','S21':'weather','S22':'emotion','S23':'body','S29':'country',
    'S30':'planet','S32':'number','S35':'tree','S36':'gemstone','S37':'mythical',
    'S38':'occupation','S39':'genre','S40':'currency','S41':'popstar','S42':'rockband',
    'S43':'usstate','S44':'worldcapital','S45':'river','S46':'president',
    'S47':'element','S48':'constellation','S49':'actor','S50':'athlete',
    'S51':'landmark','S52':'fictional',
  };
  if (catMap[rule.id]) return CATEGORY_POOL[catMap[rule.id]] || [];
  if (rule.id === 'S05') return [...SILENT_SET];
  if (rule.id === 'S14') return [...PALINDROME_LIST];
  if (rule.id === 'S56') return [...COMPOUND_SET];
  if (rule.id === 'S57') return [...SYLLABLE_SET];

  // Computational rules — single-word entries only
  const allWords = [...new Set([
    ...GENERAL_WORDS,
    ...Object.entries(CATEGORY_POOL)
      .filter(([cat]) => !MULTIWORD_CATS.has(cat))
      .flatMap(([,words]) => words),
    ...[...SILENT_SET],
  ])].filter(w => !isMultiWord(w));

  return VOWEL_RULE_IDS.has(rule.id)
    ? allWords.filter(w => !w.includes('Y'))
    : allWords;
}

function noYFilter(rule, words) {
  return VOWEL_RULE_IDS.has(rule.id) ? words.filter(w => !w.includes('Y')) : words;
}

// Single-word only pool for computational rules and pair phases
function getSingleWordPool() {
  return [...new Set([
    ...GENERAL_WORDS,
    ...Object.entries(CATEGORY_POOL)
      .filter(([cat]) => !MULTIWORD_CATS.has(cat))
      .flatMap(([,words]) => words),
    ...[...SILENT_SET],
  ])].filter(w => !isMultiWord(w));
}

function buildSinglePhase(rule, count, rng, usedWords) {
  const pool     = getPoolForRule(rule);
  const truePool = pool.filter(w => rule.check(w) && !usedWords.has(w));

  // False pool: broad single-word pool for computational rules
  // For category rules: all words not matching the rule
  const broadSingle = noYFilter(rule, getSingleWordPool())
    .filter(w => !rule.check(w) && !usedWords.has(w));

  // For category rules pull from all words including other category entries
  const falsePool = CAT_RULE_IDS.has(rule.id)
    ? [...new Set([
        ...pool.filter(w => !rule.check(w) && !usedWords.has(w)),
        ...broadSingle,
      ])]
    : broadSingle;

  const half       = Math.floor(count / 2);
  const trueCount  = half;
  const falseCount = count - half;

  // ── Distractor logic: fill up to 50% of false slots from curated distractors ──
  const distractorSlots = Math.floor(falseCount * 0.5);
  const rawDistractors  = (DISTRACTOR_POOL[rule.id] || [])
    .filter(w => !rule.check(w) && !usedWords.has(w));
  const distractorWords = pickN(rawDistractors, distractorSlots, rng);
  distractorWords.forEach(w => usedWords.add(w));

  // Backfill remaining false slots from the broad pool (excluding used)
  const backfillPool  = falsePool.filter(w => !usedWords.has(w));
  const backfillCount = falseCount - distractorWords.length;
  const backfillWords = pickN(backfillPool, backfillCount, rng);

  if (truePool.filter(w => !usedWords.has(w)).length < trueCount) return null;
  const trueWords = pickN(truePool.filter(w => !usedWords.has(w)), trueCount, rng);
  if (trueWords.length < trueCount) return null;
  if (distractorWords.length + backfillWords.length < falseCount) return null;

  trueWords.forEach(w   => usedWords.add(w));
  backfillWords.forEach(w => usedWords.add(w));

  const falseWords = [...distractorWords, ...backfillWords];

  return shuffle([
    ...trueWords.map(w  => ({ word: w, shouldAccept: true })),
    ...falseWords.map(w => ({ word: w, shouldAccept: false })),
  ], rng);
}

function buildPairPhase(rule, count, rng, usedWords) {
  const half       = Math.floor(count / 2);
  const trueCount  = half;
  const falseCount = count - half;

  const pairCatMap = { 'P09':'animal', 'P10':'color' };
  const pairCat    = pairCatMap[rule.id];

  // P11 (ends with a vowel) and P12 (same number of vowels) must exclude Y-containing words
  const PAIR_VOWEL_RULE_IDS = new Set(['P11','P12']);
  const basePool = pairCat
    ? CATEGORY_POOL[pairCat]
    : getSingleWordPool();
  const allWords = PAIR_VOWEL_RULE_IDS.has(rule.id)
    ? basePool.filter(w => !w.includes('Y'))
    : basePool;

  let truePairs  = [];
  let falsePairs = [];
  let attempts   = 0;

  while (truePairs.length < trueCount && attempts < 5000) {
    attempts++;
    const l = pick(allWords, rng);
    const r = pick(allWords, rng);
    if (l===r) continue;
    if (usedWords.has(l)||usedWords.has(r)) continue;
    if (usedWords.has(l+'+'+r)||usedWords.has(r+'+'+l)) continue;
    if (!rule.check(l,r)) continue;
    truePairs.push({ left:l, right:r, shouldAccept:true });
    usedWords.add(l); usedWords.add(r); usedWords.add(l+'+'+r);
  }
  attempts = 0;
  while (falsePairs.length < falseCount && attempts < 5000) {
    attempts++;
    const l = pick(allWords, rng);
    const r = pick(allWords, rng);
    if (l===r) continue;
    if (usedWords.has(l)||usedWords.has(r)) continue;
    if (usedWords.has(l+'+'+r)||usedWords.has(r+'+'+l)) continue;
    if (rule.check(l,r)) continue;
    falsePairs.push({ left:l, right:r, shouldAccept:false });
    usedWords.add(l); usedWords.add(r); usedWords.add(l+'+'+r);
  }

  if (truePairs.length < trueCount || falsePairs.length < falseCount) return null;
  return shuffle([...truePairs, ...falsePairs], rng);
}

function buildMixedPhase(rule, count, rng, usedWords) {
  const pairCount   = Math.floor(count / 2);
  const singleCount = count - pairCount;
  const half        = Math.floor(singleCount / 2);

  const pool     = getPoolForRule(rule);
  const truePool = pool.filter(w => rule.check(w) && !usedWords.has(w));

  const broadSingle = noYFilter(rule, getSingleWordPool())
    .filter(w => !rule.check(w) && !usedWords.has(w));

  const falsePool = CAT_RULE_IDS.has(rule.id)
    ? [...new Set([
        ...pool.filter(w => !rule.check(w) && !usedWords.has(w)),
        ...broadSingle,
      ])]
    : broadSingle;

  // ── Distractor logic: 50% of single false slots from distractors ──
  const singleFalseCount  = singleCount - half;
  const distractorSlots   = Math.floor(singleFalseCount * 0.5);
  const rawDistractors    = (DISTRACTOR_POOL[rule.id] || [])
    .filter(w => !rule.check(w) && !usedWords.has(w));
  const distractorWords   = pickN(rawDistractors, distractorSlots, rng);
  distractorWords.forEach(w => usedWords.add(w));

  const backfillPool  = falsePool.filter(w => !usedWords.has(w));
  const backfillCount = singleFalseCount - distractorWords.length;
  const backfillWords = pickN(backfillPool, backfillCount, rng);

  const trueWords  = pickN(truePool.filter(w => !usedWords.has(w)), half, rng);
  const falseWords = [...distractorWords, ...backfillWords];

  if (trueWords.length < half || falseWords.length < singleFalseCount) return null;

  trueWords.forEach(w   => usedWords.add(w));
  backfillWords.forEach(w => usedWords.add(w));

  const singleItems = shuffle([
    ...trueWords.map(w  => ({ format:'single', word:w, shouldAccept:true })),
    ...falseWords.map(w => ({ format:'single', word:w, shouldAccept:false })),
  ], rng);

  // R3 pairs use single-word rules — both words must satisfy rule
  // For category rules, sample true pairs directly from the category pool (avoids needle-in-haystack)
  // For false pairs, sample from the broad single-word pool
  const fullSinglePool = noYFilter(rule, getSingleWordPool()).filter(w => !isMultiWord(w));
  // True pair pool: words that satisfy the rule and are single-word
  const truePairPool  = fullSinglePool.filter(w => rule.check(w) && !usedWords.has(w));
  // False pair pool: words from broad pool that do NOT both satisfy — sample the broad pool
  const falsePairPool = fullSinglePool;

  const halfP     = Math.floor(pairCount / 2);
  let truePairs   = [];
  let falsePairs  = [];
  let att         = 0;

  // Build true pairs from truePairPool (direct sampling — efficient for category rules)
  const shuffledTruePairPool = shuffle([...truePairPool], rng);
  for (let i = 0; i < shuffledTruePairPool.length - 1 && truePairs.length < halfP; i++) {
    const l = shuffledTruePairPool[i];
    if (usedWords.has(l)) continue;
    for (let j = i + 1; j < shuffledTruePairPool.length && truePairs.length < halfP; j++) {
      const r = shuffledTruePairPool[j];
      if (usedWords.has(r)) continue;
      if (usedWords.has(l+'+'+r)) continue;
      if (!rule.check(l) || !rule.check(r)) continue;
      truePairs.push({ format:'pair', left:l, right:r, shouldAccept:true });
      usedWords.add(l); usedWords.add(r); usedWords.add(l+'+'+r);
      break;
    }
  }

  // Build false pairs via random sampling (at least one word must fail rule)
  att = 0;
  while (falsePairs.length < pairCount - halfP && att < 3000) {
    att++;
    const l = pick(falsePairPool, rng);
    const r = pick(falsePairPool, rng);
    if (l===r) continue;
    if (usedWords.has(l)||usedWords.has(r)||usedWords.has(l+'+'+r)) continue;
    if (rule.check(l)&&rule.check(r)) continue;
    falsePairs.push({ format:'pair', left:l, right:r, shouldAccept:false });
    usedWords.add(l); usedWords.add(r); usedWords.add(l+'+'+r);
  }

  if (truePairs.length < halfP || falsePairs.length < pairCount - halfP) return null;
  const pairItems = shuffle([...truePairs, ...falsePairs], rng);
  return shuffle([...singleItems, ...pairItems], rng);
}

// ══════════════════════════════════════════════════════════════════
// Rule picker — enforces family grouping
// ══════════════════════════════════════════════════════════════════
function pickDistinctRules(rng, recentRules, dayNumber) {
  const recent         = recentRules || new Set();
  const structFamilies = ['PATTERN','SHAPE','VOWEL','LANGUAGE'];
  const knowFamilies   = ['WORLD','CULTURE'];
  const pairFamilies   = ['PATTERN','SHAPE','VOWEL','WORLD'];

  // Alternate supergroups by day so every puzzle has structural + knowledge rounds
  const r1Super = (dayNumber % 2 === 1) ? 'STRUCTURAL' : 'KNOWLEDGE';
  const r3Super = r1Super === 'STRUCTURAL' ? 'KNOWLEDGE' : 'STRUCTURAL';

  const r1FamilyPool = r1Super === 'STRUCTURAL' ? structFamilies : knowFamilies;
  const r3FamilyPool = r3Super === 'STRUCTURAL' ? structFamilies : knowFamilies;

  const availSingle = SINGLE_RULES.filter(r => !recent.has(r.label));
  const availPair   = PAIR_RULES.filter(r => !recent.has(r.label));
  const singlePool  = availSingle.length >= 10 ? availSingle : SINGLE_RULES;
  const pairPool    = availPair.length >= 3    ? availPair   : PAIR_RULES;

  function pickFamilyRules(superFamilies, needed, pool, exclude) {
    const ex = exclude || [];
    const filteredPool = pool.filter(r => !ex.find(x => x.label === r.label));
    const shuffledFamilies = shuffle([...superFamilies], rng);
    for (const primaryFam of shuffledFamilies) {
      const adjacent = ADJACENT_FAMILIES[primaryFam];
      const eligible = filteredPool.filter(r => adjacent.has(r.family));
      const shuffled = shuffle(eligible, rng);
      if (shuffled.length >= needed) return shuffled.slice(0, needed);
    }
    // Fallback: any rule from supergroup
    const fallback = shuffle(
      filteredPool.filter(r => superFamilies.some(f => ADJACENT_FAMILIES[f].has(r.family))),
      rng
    );
    if (fallback.length >= needed) return fallback.slice(0, needed);
    // Last resort: ignore exclude
    const last = shuffle(pool.filter(r => superFamilies.some(f => ADJACENT_FAMILIES[f].has(r.family))), rng);
    return last.slice(0, needed);
  }

  const r3Pool  = singlePool.filter(r => !r.r1Only);
  const r1Rules = pickFamilyRules(r1FamilyPool, 2, singlePool);
  const r3Rules = pickFamilyRules(r3FamilyPool, 4, r3Pool, r1Rules);
  const r2Rules = pickFamilyRules(pairFamilies, 3, pairPool);

  return { r1Rules, r2Rules, r3Rules };
}

// ══════════════════════════════════════════════════════════════════
// Puzzle builder
// ══════════════════════════════════════════════════════════════════
const LAUNCH_UTC = Date.UTC(2026, 2, 13);

function utcDateString(dayNumber) {
  const ms = LAUNCH_UTC + (dayNumber - 1) * 86400000;
  const d  = new Date(ms);
  return d.toLocaleDateString('en-US', { timeZone:'UTC', year:'numeric', month:'long', day:'numeric' });
}

function buildPuzzle(dayNumber, recentWords, recentRules) {
  const usedBase = new Set(recentWords || []);
  let attempts   = 0;

  while (attempts < 50) {
    attempts++;
    const rngLocal  = makePrng(dayNumber * 31337 + 99991 + attempts * 7);
    const usedLocal = new Set(usedBase);
    const { r1Rules, r2Rules, r3Rules } = pickDistinctRules(rngLocal, recentRules, dayNumber);

    const r1p0 = buildSinglePhase(r1Rules[0], 15, rngLocal, usedLocal); if (!r1p0) continue;
    const r1p1 = buildSinglePhase(r1Rules[1], 15, rngLocal, usedLocal); if (!r1p1) continue;

    const r2p0 = buildPairPhase(r2Rules[0], 10, rngLocal, usedLocal); if (!r2p0) continue;
    const r2p1 = buildPairPhase(r2Rules[1], 10, rngLocal, usedLocal); if (!r2p1) continue;
    const r2p2 = buildPairPhase(r2Rules[2], 10, rngLocal, usedLocal); if (!r2p2) continue;

    const r3p0 = buildMixedPhase(r3Rules[0], 10, rngLocal, usedLocal); if (!r3p0) continue;
    const r3p1 = buildMixedPhase(r3Rules[1], 10, rngLocal, usedLocal); if (!r3p1) continue;
    const r3p2 = buildMixedPhase(r3Rules[2], 10, rngLocal, usedLocal); if (!r3p2) continue;
    const r3p3 = buildMixedPhase(r3Rules[3], 10, rngLocal, usedLocal); if (!r3p3) continue;

    return {
      day:    dayNumber,
      number: String(dayNumber).padStart(3, '0'),
      date:   utcDateString(dayNumber),
      rounds: [
        {
          id:0, label:'ROUND 1', name:'The Switch',
          type:'single', total:30, inversionPoints:[15],
          rules: [r1Rules[0].label, r1Rules[1].label],
          words: [...r1p0, ...r1p1],
        },
        {
          id:1, label:'ROUND 2', name:'Pairs',
          type:'pairs', total:30, inversionPoints:[10,20],
          rules: [r2Rules[0].label, r2Rules[1].label, r2Rules[2].label],
          pairs: [...r2p0, ...r2p1, ...r2p2],
        },
        {
          id:2, label:'ROUND 3', name:'Rule Breaker',
          type:'mixed', total:40, inversionPoints:[10,20,30],
          rules: [r3Rules[0].label, r3Rules[1].label, r3Rules[2].label, r3Rules[3].label],
          items: [...r3p0, ...r3p1, ...r3p2, ...r3p3],
        },
      ],
    };
  }
  throw new Error(`Failed to build puzzle for day ${dayNumber} after ${attempts} attempts`);
}

// ══════════════════════════════════════════════════════════════════
// Validation
// ══════════════════════════════════════════════════════════════════
function validatePuzzle(puzzle) {
  const errors = [];
  const singleRuleMap = Object.fromEntries(SINGLE_RULES.map(r => [r.label, r]));
  const pairRuleMap   = Object.fromEntries(PAIR_RULES.map(r => [r.label, r]));

  puzzle.rounds.forEach(rd => {
    let phase = 0;
    const items = rd.type==='single' ? rd.words
                : rd.type==='pairs'  ? rd.pairs
                : rd.items;

    // Check total count
    if (items.length !== rd.total) {
      errors.push(`R${rd.id}: expected ${rd.total} items, got ${items.length}`);
    }

    items.forEach((item, i) => {
      if (rd.inversionPoints.includes(i)) phase++;
      const ruleLabel = rd.rules[phase];

      if (rd.type==='single' || (rd.type==='mixed' && item.format==='single')) {
        const rule = singleRuleMap[ruleLabel];
        if (!rule) { errors.push(`R${rd.id} i${i}: no rule for "${ruleLabel}"`); return; }

        // Guard: multi-word items must only appear under category rules
        if (isMultiWord(item.word) && !CAT_RULE_IDS.has(rule.id)) {
          errors.push(`R${rd.id} i${i}: multi-word "${item.word}" used under computational rule "${ruleLabel}"`);
          return;
        }

        const computed = rule.check(item.word);
        if (computed !== item.shouldAccept) {
          errors.push(`R${rd.id} i${i} "${item.word}" [${ruleLabel}]: computed=${computed} expected=${item.shouldAccept}`);
        }
      } else {
        // Pair item
        const isPairRule = !!pairRuleMap[ruleLabel];
        if (isPairRule) {
          const rule    = pairRuleMap[ruleLabel];
          const computed = rule.check(item.left, item.right);
          if (!!computed !== item.shouldAccept) {
            errors.push(`R${rd.id} i${i} "${item.left}/${item.right}" [${ruleLabel}]: computed=${computed} expected=${item.shouldAccept}`);
          }
        } else {
          // R3 mixed pairs use single-word rules — both must satisfy
          const rule = singleRuleMap[ruleLabel];
          if (!rule) { errors.push(`R${rd.id} i${i}: no rule for "${ruleLabel}"`); return; }
          const computed = rule.check(item.left) && rule.check(item.right);
          if (!!computed !== item.shouldAccept) {
            errors.push(`R${rd.id} i${i} "${item.left}/${item.right}" [${ruleLabel}]: computed=${computed} expected=${item.shouldAccept}`);
          }
        }
      }
    });

    // Check no consecutive-day supergroup clash (warn, not error)
    // This is enforced at pick time, so just verify family consistency
    const roundRules = rd.rules.map(l => singleRuleMap[l] || pairRuleMap[l]).filter(Boolean);
    const supergroups = new Set(roundRules.map(r => r.supergroup));
    if (supergroups.size > 1 && rd.type !== 'pairs') {
      errors.push(`R${rd.id}: mixed supergroups in round — ${[...supergroups].join(', ')}`);
    }
  });

  return errors;
}

// ══════════════════════════════════════════════════════════════════
// Main — batch generation
// ══════════════════════════════════════════════════════════════════
const BATCH_SIZE = 30;
const WINDOW     = 30;
const recentPath  = path.join(__dirname, 'recently-used.json');
const puzzlesPath = path.join(__dirname, 'puzzles.json');

const resetMode = process.argv.includes('--reset');
if (resetMode) {
  if (fs.existsSync(recentPath)) fs.unlinkSync(recentPath);
  console.log('✓ recently-used.json cleared. Next run starts fresh.\n');
  process.exit(0);
}

let existingPuzzles = {};
if (fs.existsSync(puzzlesPath)) {
  try { existingPuzzles = JSON.parse(fs.readFileSync(puzzlesPath)); } catch {}
}
const existingDays = Object.keys(existingPuzzles).map(Number).sort((a,b)=>a-b);
const lastDay      = existingDays.length > 0 ? existingDays[existingDays.length-1] : 0;
const startDay     = lastDay + 1;
const endDay       = lastDay + BATCH_SIZE;

const puzzles    = {};
let totalErrors  = 0;
const wordsByDay = {};
const rulesByDay = {};

// Load word history from previous batch
if (fs.existsSync(recentPath)) {
  try {
    const recentData = JSON.parse(fs.readFileSync(recentPath));
    if (Array.isArray(recentData)) {
      wordsByDay[startDay-1] = new Set(recentData);
    } else {
      Object.entries(recentData).forEach(([day,words]) => {
        wordsByDay[Number(day)] = new Set(words);
      });
    }
    console.log(`Loaded word history from previous batch`);
  } catch {}
}

// Pre-populate rules from existing puzzles for cross-batch rule blocking
Object.entries(existingPuzzles).forEach(([day, puzzle]) => {
  rulesByDay[Number(day)] = new Set(puzzle.rounds.flatMap(rd => rd.rules));
});

console.log(`Generating Days ${startDay}–${endDay} (${BATCH_SIZE}-day batch)\n`);

function extractWords(puzzle) {
  const words = new Set();
  puzzle.rounds.forEach(rd => {
    const items = rd.type==='single' ? rd.words
                : rd.type==='pairs'  ? rd.pairs
                : rd.items;
    items.forEach(item => {
      if (item.word)  words.add(item.word);
      if (item.left)  words.add(item.left);
      if (item.right) words.add(item.right);
    });
  });
  return words;
}

function extractRules(puzzle) {
  return new Set(puzzle.rounds.flatMap(rd => rd.rules));
}

for (let day = startDay; day <= endDay; day++) {
  let puzzle;
  try {
    const windows  = [WINDOW, 14, 7, 0];
    let built      = false;
    const prevRules = rulesByDay[day-1] || new Set();

    for (const win of windows) {
      const windowWords = new Set();
      for (let d = day-win; d < day; d++) {
        if (wordsByDay[d]) wordsByDay[d].forEach(w => windowWords.add(w));
      }
      try {
        puzzle = buildPuzzle(day, windowWords, prevRules);
        if (win < WINDOW) console.log(`  Day ${day}: relaxed to ${win}-day window`);
        built = true;
        break;
      } catch {}
    }
    if (!built) throw new Error('all windows exhausted');
  } catch (e) {
    console.error(`Day ${day}: GENERATION FAILED — ${e.message}`);
    process.exit(1);
  }

  const errors = validatePuzzle(puzzle);
  if (errors.length > 0) {
    console.error(`Day ${day}: ${errors.length} validation error(s):`);
    errors.forEach(e => console.error('  ' + e));
    totalErrors += errors.length;
  } else {
    console.log(`Day ${String(day).padStart(3,'0')} ✓  ${puzzle.date}`);
    puzzle.rounds.forEach(r => {
      const families = r.rules.map(label => {
        const rule = [...SINGLE_RULES,...PAIR_RULES].find(x=>x.label===label);
        return rule ? rule.family : '?';
      });
      console.log(`       R${r.id+1}: [${families.join('][')}] ${r.rules.join(' → ')}`);
    });
  }

  wordsByDay[day] = extractWords(puzzle);
  rulesByDay[day] = extractRules(puzzle);
  puzzles[day]    = puzzle;
}

if (totalErrors > 0) {
  console.error(`\n${totalErrors} total validation error(s). Not writing output.`);
  process.exit(1);
}

const merged = { ...existingPuzzles, ...puzzles };
fs.writeFileSync(puzzlesPath, JSON.stringify(merged, null, 2));
console.log(`\n✓ puzzles.json updated — Days 1–${endDay}`);

const recentData = {};
for (let day = startDay; day <= endDay; day++) {
  if (wordsByDay[day]) recentData[day] = [...wordsByDay[day]];
}
fs.writeFileSync(recentPath, JSON.stringify(recentData, null, 2));
console.log(`✓ recently-used.json saved — ${BATCH_SIZE} days of word history`);
console.log(`\nNext run will generate Days ${endDay+1}–${endDay+BATCH_SIZE}`);
